node {
  timeout(BUILD_TIMEOUT.toInteger()) {
    checkout scm

    try {
      stage("load commons environment variables") {
        @Library("commons") _
      }

      stage("pre build") {
        docker_.login()
        build.setup([
          repo: "astrotrain-manager",
          rollbar_token: "ASTROTRAIN_MANAGER_ROLLBAR_ACCESS_TOKEN",
          swarm_key: [ id: "ASTROTRAIN_MANAGER_KEY", name: "key.pem" ]
        ])
      }

      stage("build") {
        docker_.build([ dockerfile: "docker/production.Dockerfile" ])
        docker_.run("npm run test")
      }

      stage("post build") {
        build.tagAndPush()
        build.finish()
      }

    } catch (err) {
      build.fail()
    } finally {
      deleteDir()
    }
  }
}
